/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f407xx.h"
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void delay(void){
	uint32_t i = 0x000FFFFF;

	while(i > 0){
		i--;
	}
}
int main(void)
{
    /* Loop forever */
	uint32_t *myptr = 0x40023830;
	*myptr |= (1<<3);

	GPIOD->MODER	= 0x55000000;
	GPIOD->OTYPER 	= 0xFF000000;
	GPIOD->OSPEEDR 	= 0xFF000000;
	GPIOD->PUPDR    = 0x00000000;

	while(1){

		GPIOD->ODR = 0x0000F000;
		delay();
		GPIOD->ODR = 0x00000000;
		delay();
	}
}
